### ISSUE TITLE
Introduce GraphiQL on /

### ISSUE THREAD

**Issue by Albert221** [Albert221/mpra#2]
For developers convenience, there should be GraphiQL exposed, best on the root path `/`, so that they will be able to firstly test the API and get hands-on experience which would convince them more on using it.

**Comment by ananichev** [comment]
Let me take this one too :)

**Comment by shabinesh** [comment]
@ananichev Have you started on this already?

**Comment by ananichev** [comment]
@shabinesh yes, #4

**Comment by Albert221** [comment]
Resolved in https://github.com/Albert221/medicinal-products-registry-api/commit/7ab38a67ab0f09a8128b7b158948aa8e6d6d3de6
